In [1]:
import pandas as pd

In [17]:
df1 = pd.read_csv('users.csv')

In [8]:
df2 = pd.read_csv('spam_users2.csv')

In [14]:
df1 = df1.append(df2, ignore_index=True, verify_integrity=False)

In [16]:
df1.to_csv('users.csv')

In [20]:
tw1 = pd.read_csv('tweets.csv', sep='\t', encoding='utf-8-sig')

/home/matteo/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2785: DtypeWarning: Columns (1,8,18,20,23) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [23]:
tw1.head()

,contributors,coordinates,created_at,display_text_range,extended_entities,favorite_count,favorited,full_text,geo,id,...,quoted_status_id,quoted_status_id_str,quoted_status_permalink,retweet_count,retweeted,retweeted_status,source,truncated,url,user_id
0,NaN,NaN,Fri Dec 05 02:19:38 +0000 2014,"[0, 55]",NaN,2,False,Read the History of David Gates http://t.co/Y...,NaN,540691938639630336,...,NaN,NaN,NaN,2,False,NaN,"<a href=""http://tweetadder.com"" rel=""nofollow""...",False,http://oldiesmusic.hubpages.com/hub/History-of...,347491211
1,NaN,NaN,Fri Dec 05 01:58:53 +0000 2014,"[0, 57]",NaN,0,False,Caring For Your New Garage Floors http://t.co...,NaN,540686715145695232,...,NaN,NaN,NaN,0,False,NaN,"<a href=""http://tweetadder.com"" rel=""nofollow""...",False,http://garage-info.hubpages.com/hub/Caring-For...,347491211
2,NaN,NaN,Fri Dec 05 01:54:48 +0000 2014,"[0, 131]",NaN,0,False,Check out these awesome baseball t-shirts &amp...,NaN,540685691332857856,...,NaN,NaN,NaN,0,False,NaN,"<a href=""http://tweetadder.com"" rel=""nofollow""...",False,http://www.cafepress.com/baseballiguide,347491211
3,NaN,NaN,Fri Dec 05 01:42:46 +0000 2014,"[0, 55]",NaN,0,False,Read the History of Patsy Cline http://t.co/v...,NaN,540682660352233472,...,NaN,NaN,NaN,0,False,NaN,"<a href=""http://tweetadder.com"" rel=""nofollow""...",False,http://oldiesmusic.hubpages.com/hub/History-of...,347491211
4,NaN,NaN,Fri Dec 05 01:22:32 +0000 2014,"[0, 59]",NaN,0,False,Great Introduction to Snooky Lanson http://t....,NaN,540677567481532416,...,NaN,NaN,NaN,0,False,NaN,"<a href=""http://tweetadder.com"" rel=""nofollow""...",False,http://oldiesmusic.hubpages.com/hub/Introducti...,347491211

In [25]:
tw2 = pd.read_csv('spam_tweets2.csv', sep='\t', encoding='utf-8-sig')

/home/matteo/anaconda3/lib/python3.6/site-packages/IPython/core/interactiveshell.py:2785: DtypeWarning: Columns (1,8,18,20,23,26) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [26]:
tw2.head()

,contributors,coordinates,created_at,display_text_range,extended_entities,favorite_count,favorited,full_text,geo,id,...,quoted_status_id,quoted_status_id_str,quoted_status_permalink,retweet_count,retweeted,retweeted_status,source,truncated,url,user_id
0,NaN,NaN,Tue Sep 08 09:30:10 +0000 2015,"[0, 89]",NaN,5,False,DisneyWorld: The post DisneyWorld appeared fir...,NaN,641181725389754368,...,NaN,NaN,NaN,0,False,NaN,"<a href=""http://twitterfeed.com"" rel=""nofollow...",False,http://bit.ly/1K4GbzD,7248952
1,NaN,NaN,Thu Jan 22 14:40:58 +0000 2015,"[0, 136]",NaN,0,False,Environmental Impact of Dams: Environmental Im...,NaN,558273119656239104,...,NaN,NaN,NaN,0,False,NaN,"<a href=""http://twitterfeed.com"" rel=""nofollow...",False,http://bit.ly/1CjZ25j,7248952
2,NaN,NaN,Wed Jan 21 22:44:35 +0000 2015,"[0, 136]",NaN,0,False,Soil Pollution: Soil Pollution Soil pollution ...,NaN,558032439113940992,...,NaN,NaN,NaN,0,False,NaN,"<a href=""http://twitterfeed.com"" rel=""nofollow...",False,http://bit.ly/1yK3wzw,7248952
3,NaN,NaN,Wed Jan 21 20:21:18 +0000 2015,"[0, 136]",NaN,0,False,Wildlife Conservation: Wildlife Conservation W...,NaN,557996380002611200,...,NaN,NaN,NaN,0,False,NaN,"<a href=""http://twitterfeed.com"" rel=""nofollow...",False,http://bit.ly/1CQwEGa,7248952
4,NaN,NaN,Wed Jan 21 20:21:18 +0000 2015,"[0, 136]",NaN,0,False,Deforestation: Deforestation Deforestation is ...,NaN,557996379226644480,...,NaN,NaN,NaN,0,False,NaN,"<a href=""http://twitterfeed.com"" rel=""nofollow...",False,http://bit.ly/1CQwG0Q,7248952

In [24]:
tw1.shape

(362092, 31)

In [27]:
tw2.shape

(56892, 31)

In [28]:
tw1 = tw1.append(tw2, ignore_index=True, verify_integrity=False)

In [30]:
tw1.shape

(418984, 31)

In [31]:
tw1.to_csv('tweets.csv', sep='\t', encoding='utf-8-sig')